name: 构建 Windows 应用

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: 设置 Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install pyqt5 pyperclip pyinstaller
    
    - name: 使用 PyInstaller 构建
      run: |
        pyinstaller --onefile --windowed --add-data "keywords.txt;." --name "日志搜索工具" log_search_tool.py
    
    - name: 上传构建结果
      uses: actions/upload-artifact@v3
      with:
        name: 日志搜索工具
        path: dist/日志搜索工具.exe